def table_has_rows(engine, table_name: str) -> bool:
    ...

def silver_stations_ready(engine) -> bool:
    ...

def bronze_weather_ready(engine) -> bool:
    ...

def silver_weather_ready(engine) -> bool:
    ...
